[package]
name = "batt"
version = "0.1.0"
authors = ["gliontos <sdi1600094@di.uoa.gr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.11.0"
logos-derive = "0.11.0"
colored = "1.9.3"
lazy_static = "1.4.0"